### ISSUE TITLE
Determine dependent VS Code engine version

### ISSUE THREAD

**Issue by felicio** [prettier-snippets/vscode-prettier-snippets-react#1]
Currently the extension is built against `vscode@1.3.0`, which however doesn't support [Snippet Completion](https://code.visualstudio.com/updates/v1_8#_snippet-completions) API. That is present in `1.8.0`. And if we'd like to support Multi-root Workspace we should build on the latest stable version, being `1.18.0`.

**Comment by felicio** [comment]
We're extending Electron-based app and as such it is locked down to a certain `node` version. An information that will tells us for example what ES features can be used.

**Comment by felicio** [comment]
In the next PR I can bump the version. `npm install` will be required.

**Comment by prichodko** [comment]
Good catch. I can't find a way how to see in the documentation, what version is API supported from.

**Comment by felicio** [comment]
I can only tell when something is missing, because IntelliSense will be silent in that case.
