### ISSUE TITLE
Support standalone methods

### ISSUE THREAD

**Issue by prichodko** [prettier-snippets/vscode-prettier-snippets-react#17]
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACSBbADtBMDqAlgDbECyEArrABQCUqwAOlKkzACoCCAQgMocA8gAUA+gAYWqAL4gANCAhYYhaAGdkoAIZqYyAGZbiauAoBGAJy1gA1nBh8s1wlADmyGBcqmQAEwhgBkYmCi4mFjDCVq4YWkHGPgBWagAePFa29nxaGHAAMi5w8SGKlDBYZQBMxT5OFuHIIGZaZgCexNDyIFgWLgSEvjAAFsgAHOIKPRAm+FZYHl4+FnAAjpSEy1FaMXFIhgkKJhiEC96HLq7EcACKlBDwNQowLUSDI0iVT1YkFwDCEBhYo0oLgupQTBwWho9sE4NJpEA

**Comment by prichodko** [comment]
Right now only I see only two options how to make this syntax valid: 
https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNNIBbAB2gRgHUBLAGzYFkIBXWACgCUJcplIwAKgEEAQgGUJAeQAKAfQAMogL7kdUcjXpRGrDtz5ZiQogD4RFTNPlK1mqHpAAaEBFowW6MigAIYYyABmwWxocN44AE7BYADWcDBytEksUADmyDDxPLEgACYQYBFRMd7ZMfEwyok51MGV0cV4aAAeMokpaXLB1HAAMtlwbdU+PDC0MwBMk8WZ8XXIIDjBOACebNBeILTx2cwsJTAAFsgAHOreRxAxTIm0+YXF8XAAjjwsn43BZqtJCRdreGLUFhvIrg7I5NhwACKPAg8CW3hgW1Y5yuSHmGMS7DhAGEINQWusoAwDjwYhItmgllotEA

What do you think @felicio?

**Comment by felicio** [comment]
```javascript
AFTER_FORMATTING_STRIP_METHOD_NAME_AND_FUNCITON_KEYWORD_TOKEN: function mount() {
 	TABSTOP_0
 }
```

**Comment by prichodko** [comment]
Oh! Totally forgot about `function` keyword  🤣.

But, what's that syntax?

Maybe we could go just with:
```javascript
function DELETE_FUNCTION_KEYWORD_mount() {
  TABSTOP_0
}
```
?

**Comment by felicio** [comment]
```js
const re = /(\w+): function /g
'mount: function mount() {}'.replace(re, '')
```

**Comment by felicio** [comment]
or better 

```js
const re = /(^\S\w+)/g // shorthand prop name (ES2015)
'mount() {}'.replace(re, '$1: function $1')
```

**Comment by felicio** [comment]
Is shorthand prop what you meant?
